apiVersion: v1
kind: Pod
metadata:
  name: mcp-bridge
  labels:
    app: mcp-bridge
spec:
  containers:
    - name: mcp-bridge-container
      image: mcp-bridge-mcp-bridge:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      env:
        - name: MCP_BRIDGE__CONFIG__FILE
          value: /mcp_bridge/config.json
      volumeMounts:
        - name: config-volume
          mountPath: /mcp_bridge/config.json
          subPath: config.json
  volumes:
    - name: config-volume
      configMap:
        name: mcp-bridge-config
