name: mcp-server-build-and-push

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.venv'
      - '.git'
      - 'k8s'
      - '*.lock'
      - '.gitignore'
      - 'Makefile'
      - 'README.md'
      - 'pyproject.toml'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: mcp-bridge
            context: ./MCP-Bridge
            dockerfile: ./MCP-Bridge/Dockerfile
          - name: mcp-context7
            context: ./mcp-dockerfiles
            dockerfile: ./mcp-dockerfiles/context7.dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ github.sha }}

    - name: Push to infra-cd
      run: |
        git config --global user.name 'middlek'
        git config --global user.email 'kmiddlecenter@gmail.com'
        git clone https://${{ secrets.GH_TOKEN }}@github.com/MiddleKD/infra-cd.git
        cd infra-cd/mcp-server/kustomize/overlays/dev
        yq eval '.images[].newTag = "${{ github.sha }}"' -i kustomization.yaml
        git add .
        git commit -m "Update from GitHub Actions" || echo "No changes to commit"
        git push
