name: mcp-server-build-and-push

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.venv'
      - '.git'
      - 'k8s'
      - '*.lock'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: mcp-bridge
            context: MCP-Bridge
            dockerfile: MCP-Bridge/Dockerfile
          - name: mcp-context7
            context: mcp-dockerfile
            dockerfile: mcp-dockerfile/context7.dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata tags for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/mcp-server
        tags: |
          type=sha,format=long

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.service.context }}
        dockerfile: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Push to infra-cd
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git clone https://${{ secrets.GH_TOKEN }}@github.com/MiddleKD/infra-cd.git
        cd infra-cd/mcp-server/kustomize/overlays/dev
        yq eval '.images[].newTag = "${{ steps.meta.outputs.tags }}"' -i kustomization.yaml
        git add .
        git commit -m "Update from GitHub Actions" || echo "No changes to commit"
        git push
